### ISSUE TITLE
Cannot find_package the library

### ISSUE THREAD

**Issue by xEnVrE** [robotology/superimpose-mesh-lib#12]
**Description of the issue**

I am trying to use the library within an external project using CMake.

The configuration is as follows:
- OS: Ubuntu 18.04
- Installed libraries:
  - GLFW 3.2.1-1 (using `apt install libglfw3-dev`)
  - GLEW 2.0.0-5 (using `apt install libglew-dev`)
  - GLM 0.9.9~a2-2 (using `apt install libglm-dev`)
  - ASSIMP 4.1.0~dfsg-3 (using `apt install libassimp-dev`)
  - OpenCV 

The library compiles and installs succesfully using standard commands.

The testing `CMakeLists.txt` that I am using is as follows:

```
cmake_minimum_required(VERSION 3.5)

project(siml-client LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 11)

set(EXE_TARGET_NAME siml-client-exe)

find_package(SuperimposeMesh 0.10.100 REQUIRED)

set(${EXE_TARGET_NAME}_SRC src/main.cpp)

add_executable(${EXE_TARGET_NAME} ${${EXE_TARGET_NAME}_SRC} )

target_link_libraries(${EXE_TARGET_NAME} PRIVATE SI::SuperimposeMesh)

install(TARGETS ${EXE_TARGET_NAME} DESTINATION bin)
```

When I execute `cmake ../ -DASSIMP_VERBOSE=ON` I get

```
-- The CXX compiler identification is GNU 7.3.0 
-- Check for working CXX compiler: /usr/bin/c++
-- Detecting CXX compiler ABI info 
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done 
-- Found YCM: /usr/local/share/YCM (found version "0.10.1.15-20190423.4+gitba59f7f") 
-- Findassimp: ASSIMP_INCLUDE_DIR: /usr/include
-- Findassimp: ASSIMP_INCLUDE_DIRS: /usr/include 
-- Findassimp: ASSIMP_ROOT_DIR: /usr 
-- Findassimp: ASSIMP_LIBRARY_RELEASE: /usr/lib/x86_64-linux-gnu/libassimp.so 
-- Findassimp: ASSIMP_LIBRARY_DEBUG: ASSIMP_LIBRARY_DEBUG-NOTFOUND
-- Findassimp: ASSIMP_LIBRARY: /usr/lib/x86_64-linux-gnu/libassimp.so 
-- Findassimp: ASSIMP_LIBRARIES: /usr/lib/x86_64-linux-gnu/libassimp.so 
-- Findassimp: ASSIMP_LIBRARY_DIRS: /usr/lib/x86_64-linux-gnu 
-- Findassimp: Creating assimp::assimp imported target.
-- Findassimp: succesfully parsed major version. 
-- Findassimp: succesfully parsed minor version.
-- Findassimp: succesfully parsed revision version.
-- Findassimp: ASSIMP_VERSION_MAJOR: 4 
-- Findassimp: ASSIMP_VERSION_REVISION: 0 
-- Findassimp: ASSIMP_VERSION: 4.1.0 
-- Found ASSIMP: /usr/include (found version "4.1.0")
CMake Error at CMakeLists.txt:16 (find_package): 
  Found package configuration file:
   
    /usr/local/lib/cmake/SuperimposeMesh/SuperimposeMeshConfig.cmake 
  
  but it set SuperimposeMesh_FOUND to FALSE so package "SuperimposeMesh" is
  considered to be NOT FOUND.  Reason given by package: 
 
  SuperimposeMesh could not be found because dependency assimp could not be
  found.

-- Configuring incomplete, errors occurred! 
See also "/projects/superimpose-mesh-lib-client/build/CMakeFiles/CMakeOutput.log".
```

By checking the CMake trace, obtained using `cmake ../ --trace`, it seems that when
```
find_dependency(assimp)
``` 
is called, inside the config file
```
/usr/local/lib/cmake/SuperimposeMesh/SuperimposeMeshConfig.cmake
```
, then the correct module from `YCM`, i.e.

```
/usr/local/share/YCM/find-modules/Findassimp.cmake
```
, is used.
However, before the error is triggered the following lines are printed in the trace

```
(...)
/usr/local/share/YCM/find-modules/Findassimp.cmake(273):  if(NOT ASSIMP_FOUND )
/usr/local/share/YCM/find-modules/Findassimp.cmake(285):  if(COMMAND set_package_properties )
/usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake(57):  if(NOT assimp_FOUND )
/usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake(58):  set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE ${CMAKE_FIND_PACKAGE_NAME} could not be found because dependency assimp could not be found. )
/usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake(59):  set(${CMAKE_FIND_PACKAGE_NAME}_FOUND False )
/usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake(60):  return()
```

suggesting that while `ASSIMP_FOUND` is set, `assimp_FOUND`, that is checked by CMake `find_dependency`, is not.

I am attaching the entire trace to the issue.
[trace.txt](https://github.com/robotology/superimpose-mesh-lib/files/3109396/trace.txt)

**Comment by claudiofantacci** [comment]
Hi @xEnVrE, thanks for reporting this. I will try to test this as soon as possible.

**Comment by claudiofantacci** [comment]
@xEnVrE, could you please try to change `find_dependency(assimp)` in `find_dependency(ASSIMP)` please and see if it works? Thanks!

**Comment by claudiofantacci** [comment]
I found the possible source of error in YCM and will fix this.

**Comment by xEnVrE** [comment]
@claudiofantacci, meanwhile I tried what you suggested and I report the results in case it is still needed.

I changed  `find_dependency(assimp)` in `find_dependency(ASSIMP)` in `/usr/local/lib/cmake/SuperimposeMesh/SuperimposeMeshConfig.cmake`.

Then I get a different error, i.e.

```
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found YCM: /usr/local/share/YCM (found version "0.10.2")
-- Found GLEW: /usr/include (found version "2.0.0") 
-- Found OpenCV: /usr/share/OpenCV/OpenCVConfig.cmake  
-- Configuring done
CMake Error at CMakeLists.txt:13 (add_executable):
  Target "siml-client-exe" links to target "assimp::assimp" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/xenvre/test_superimpose/build
```

By looking at the trace it is clear that by using `ASSIMP`, the module from YCM, i.e. `/usr/local/share/YCM/find-modules/Findassimp.cmake`, is not used. Instead it is using `/usr/lib/x86_64-linux-gnu/cmake/assimp-4.1/assimp-config-version.cmake`.

**Comment by claudiofantacci** [comment]
Are you also `find_package(YARP)` and before `find_package(SuperimposeMash)`? If this is the case, this is probably another bug that is affecting YARP in combination with YCM that has been addressed yesterday.

**Comment by claudiofantacci** [comment]
This issue should be addressed by https://github.com/robotology/ycm/pull/253.

@xEnVrE let me know the issue you have, but I think it is unrelated to this one.

**Comment by xEnVrE** [comment]
Closing since I tested with https://github.com/robotology/ycm/pull/253 and everything is working fine now.
