### ISSUE TITLE
Correct imported target glfw3

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/superimpose-mesh-lib#2]
As reported by @traversaro in his [comment](https://github.com/robotology/superimpose-mesh-lib/commit/f111a01cb60317bec2ef10240e34e368911acbf5#commitcomment-28867972), the dependency `GLFW3` in

https://github.com/robotology/superimpose-mesh-lib/blob/8ed0186b9ca6609878f3f88a71c6d14396131dc0/CMakeLists.txt#L77

should be **lowercase**.

**Comment by traversaro** [comment]
Nitpick: that is the package name, not the imported target name (that instead is `glfw`).

**Comment by claudiofantacci** [comment]
@traversaro thanks for pointing it out, I was aware of it as that name is used for [`find_dependency()`](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html?highlight=find_dependency#command:find_dependency).

**Comment by claudiofantacci** [comment]
cc @xenvre

**Comment by claudiofantacci** [comment]
Closing this after PR #4.
