### ISSUE TITLE
YCMConfig.cmake not found

### ISSUE THREAD

**Issue by Asiyeh-Bahaloo** [robotology/superimpose-mesh-lib#22]
i have installed all dependencies, but when i try  "cmake .."  it gives :
`CMake Error at CMakeLists.txt:52 (find_package):
  By not providing "FindYCM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "YCM", but
  CMake did not find one.

  Could not find a package configuration file provided by "YCM" (requested
  version 0.10.2) with any of the following names:

    YCMConfig.cmake
    ycm-config.cmake

  Add the installation prefix of "YCM" to CMAKE_PREFIX_PATH or set "YCM_DIR"
  to a directory containing one of the above files.  If "YCM" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
`
1) i installed ycm (first i should install vim)
2) and add some path to cmake like : export CMAKE_PREFIX_PATH=~/.vim/bundle/YouCompleteMe/python/ycm
 but none of them worked. Then i realize that there is no  YCMConfig.cmake at all. So i tried to  copy this https://github.com/robotology/ycm/blob/master/YCMConfig.cmake.in to my ycm folder and add path to cmake again. This didnt work too. 
So could someone tell me please how can i get rid of this error?

**Comment by claudiofantacci** [comment]
Hi @Asiyeh-Bahaloo, thanks for using this library 🚀 

It seems that you have some problems finding `ycm`. Did you clone the repository, configure it with `cmake` and installed it? Or did you follow a different procedure?

You should do something like this (I assume you are on Unix system, but you can more or less do the same on Wndows):
```cmake
git clone https://github.com/robotology/ycm.git
cd ycm
git checkout v0.10.2
mkdir build
cd build
cmake ..
make
[sudo] make install
```
You can configure the installation folder when running the `cmake` command by passing the extra parameter `-DCMAKE_INSTALL_PREFIX=/path/to/installation/folder`. If you require admin privileges run `sudo make install`, otherwise just `make install`.

At this point you should have also installed the `YCMConfig.cmake` file that this library uses to find `ycm`. If you installed it in the default folder (which requires admin privileges) there should be nothing more to do. Just try to configure `superimpose-mesh-lib` again. Otherwise, you should add `/path/to/installation/folder` to the [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) environment variable.

**Comment by traversaro** [comment]
@claudiofantacci  Related to this, it could probably make sense to add YCM links to https://github.com/robotology/superimpose-mesh-lib/blob/master/README.md#-dependencies .

**Comment by claudiofantacci** [comment]
@traversaro thanks for spotting this, I just added YCM to the dependency list! @Asiyeh-Bahaloo sorry for the possible confusion this may have caused. Luckily, YCM is just a collection of CMake files and its installation is very simple and straightforward, with no other dependencies 👍

**Comment by Asiyeh-Bahaloo** [comment]
I was installed wrong library.

Thank you for your fast response. This solved my issue

**Comment by Akashleena** [comment]
I do have YCMConfig.cmake.in in this path /home/aleena/icubLearningTrajectories/icub/software/src/ycm/YCMConfig.cmake.in. I have yarp in this path /home/aleena/icubLearningTrajectories/icub/software/src/yarp . When I am trying to cmake in yarp I get this error  

 Could not find a package configuration file provided by "YCM" (requested
  version 0.11.0) with any of the following names:

    YCMConfig.cmake
    ycm-config.cmake

  Add the installation prefix of "YCM" to CMAKE_PREFIX_PATH or set "YCM_DIR"
  to a directory containing one of the above files.  If "YCM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!


How do I resolve this error?

**Comment by traversaro** [comment]
Hi @Akashleena , I suggest that you open a new issue in the YARP repository for this, thanks: https://github.com/robotology/yarp/issues/new/choose .

**Comment by MrHuangWenjie** [comment]
> Hi @Asiyeh-Bahaloo, thanks for using this library 🚀
> 
> It seems that you have some problems finding `ycm`. Did you clone the repository, configure it with `cmake` and installed it? Or did you follow a different procedure?
> 
> You should do something like this (I assume you are on Unix system, but you can more or less do the same on Wndows):
> 
> ```cmake
> git clone https://github.com/robotology/ycm.git
> cd ycm
> git checkout v0.10.2
> mkdir build
> cd build
> cmake ..
> make
> [sudo] make install
> ```
> 
> You can configure the installation folder when running the `cmake` command by passing the extra parameter `-DCMAKE_INSTALL_PREFIX=/path/to/installation/folder`. If you require admin privileges run `sudo make install`, otherwise just `make install`.
> 
> At this point you should have also installed the `YCMConfig.cmake` file that this library uses to find `ycm`. If you installed it in the default folder (which requires admin privileges) there should be nothing more to do. Just try to configure `superimpose-mesh-lib` again. Otherwise, you should add `/path/to/installation/folder` to the [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) environment variable.

Dear claudiofantacci,

I did exactly what you mentioned but on windows, while make or mingw32-make does not work for me after cmake ..

Do you have any advice?

Thank you!

**Comment by traversaro** [comment]
> Dear claudiofantacci,
> 
> I did exactly what you mentioned but on windows, while make or mingw32-make does not work for me after cmake ..
> 
> Do you have any advice?
> 
> Thank you!

If you want to invoke the build tools for which you generated build files for CMake in a generator-independent by running:
~~~
cmake --build . --config Release 
cmake --install . --config Release
~~~
instead of `make` and `make install` .

**Comment by MrHuangWenjie** [comment]
> > Dear claudiofantacci,
> > I did exactly what you mentioned but on windows, while make or mingw32-make does not work for me after cmake ..
> > Do you have any advice?
> > Thank you!
> 
> If you want to invoke the build tools for which you generated build files for CMake in a generator-independent by running:
> 
> ```
> cmake --build . --config Release 
> cmake --install . --config Release
> ```
> 
> instead of `make` and `make install` .

Thank you so much for help!

I think I have worked through this and successfully ran yarpserver now.

While, when I want to use yarpmotorgui, error happened as:

Error while opening device for part /icub/head and same for all parts.

the message stack ends with:
announce "/yarpmotorgui/head/sequence:o"
 * unregister "/yarpmotorgui/head/sequence:o"
Could you please give me advice on what may cause this?

Thank you very much!

**Comment by traversaro** [comment]
Hi @MrHuangWenjie, which software are you trying to install/use? I suggest that you open an issue in the repo of the software that you are trying to install (how is `yarpmotorgui` related to superimpose-mesh-lib?) describing what you are trying to do, thanks!

**Comment by MrHuangWenjie** [comment]
> Hi @MrHuangWenjie, which software are you trying to install/use? I suggest that you open an issue in the repo of the software that you are trying to install (how is `yarpmotorgui` related to superimpose-mesh-lib?) describing what you are trying to do, thanks!

Hi Traversaro,

Thank you for the suggestion. I am literally using Yarp for iCub simulation. The installation problem of YCM led me here. Fortunately, I have worked through the YCM issues. 

As exactly you advise, I should then open another issue on YARP repo.

**Comment by traversaro** [comment]
Ok! As this is about iCub simulation, feel free to open an issue in https://github.com/robotology/community . Note that if you want to install YARP + iCub and all is necessary for running the iCub simulation, you can both install manually ycm, yarp and icub (as I guess you were doing) or also follow the documentation in https://github.com/robotology/robotology-superbuild .
