### ISSUE TITLE
Is there any documentation about the rendering pipeline?

### ISSUE THREAD

**Issue by Asiyeh-Bahaloo** [robotology/superimpose-mesh-lib#23]
Hello, and thank you for your useful library. Is there any documentation of how this works? I mean how you calculate projection matrix? and how rendering is done?
I appreciate if you can refer to your code or some documentation.

**Comment by claudiofantacci** [comment]
Hi @Asiyeh-Bahaloo, thanks for reaching out!
Could you provide us more details about what you would like to know more of?

In the meantime:
- This is the part of code where we evaluare the projection matrix with comments supporting it https://github.com/robotology/superimpose-mesh-lib/blob/da269af9baf9a583e4a0cf9cea3288b7e8d037b3/src/SuperimposeMesh/src/SICAD.cpp#L1233-L1288
- The rendering pipeline is quite standard and you can basically re-create it following any OpenGL step-by-step tutorial you can find online, like [this one](https://learnopengl.com).

**Comment by Asiyeh-Bahaloo** [comment]
Thank you for your reply. This answered my first question about calculating projection matrix. I assume for rendering you could just pass this to openGL and it handles the rendering for you. Is that right?

**Comment by claudiofantacci** [comment]
> Thank you for your reply. This answered my first question about calculating projection matrix. I assume for rendering you could just pass this to openGL and it handles the rendering for you. Is that right?

Once you set up the OpenGL rendering pipeline (that you can find explained in the tutorial link I shared with you), the projection matrix is then automatically used by OpenGL.

**Comment by Asiyeh-Bahaloo** [comment]
I thought maybe you implemented it yourself and i was wondering how i can do that without extra libraries. Now it became clear that OpenGL will do the trick for me. Thank you
