### ISSUE TITLE
Fragment shader program compilation error

### ISSUE THREAD

**Issue by arrenglover** [robotology/superimpose-mesh-lib#24]
When updating to the master (also devel) branch of superimpose-mesh-lib I get the following error:
```
[SI::SICAD]Setting up shader for textured mesh model.
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR::SICAD::CTOR
ERROR:
	Failed to create shader program for textured meshes.
ERROR::SHADER::CTOR
ERROR:
	Fragment shader program compilation error.
LOG:
	
Aborted (core dumped)
```

The error comes as I create an instance of SICAD like this:
```
    SICAD si_cad(obj,
                 cam_width_, cam_height_, cam_fx_, cam_fy_, cam_cx_, cam_cy_,
                 1,
                 config.find("shader_path").asString());
```

The same code works when using the branch `render_texture`. Have some changes occured to master that could lead to failure when creating the Fragment Shader?

**Comment by arrenglover** [comment]
@xEnVrE - did you ever have a problem here?

**Comment by xEnVrE** [comment]
@arrenglover 

I think that the problem might arise if you don't have all the newer `.frag` and .`vert` files required after the recent updates to the library.

Can you please check which files do you have in the path corresponding to the output of the `config.find("shader_path").asString()` string?

Btw, If I am not wrong the library recently features new constructors, not taking the shaders path as argument, that load all the required files using an internal mechanism. You may want to use these in case you are using the default shaders and you don't require any customization.

**Comment by arrenglover** [comment]
thanks for the comments.

I tried using the .frag and .vert files (provided under test) and still got the error. 

A side questions: do you know if these new files allow you to render texture if the .obj provides it?

I'll have a look at the new constructors and see if I can remove the error.

**Comment by arrenglover** [comment]
@xEnVrE - yeah the new constructors seemed to have worked. Thanks! It must have been mismatch to my old shaders and I must have made a mistake when trying to update them.
