### ISSUE TITLE
Broken ASSIMP CMake config files

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/superimpose-mesh-lib#6]
The ASSIMP CMake config files are somewhat broken upstream (not all platform/IDE are affected), but the result is that finding the package with config files is unreliable.

The following snippet code is an ugly workaround to work under macOS, and in particular with Xcode (compiling using terminal works).

https://github.com/robotology/superimpose-mesh-lib/blob/ac23148460f4ad5d3f61063dbe10683b298e4463/src/SuperimposeMesh/CMakeLists.txt#L28-L38

As suggested by @traversaro, we could roll back to [DART's Findassimp.cmake](https://github.com/dartsim/dart/blob/master/cmake/Findassimp.cmake).

**Comment by claudiofantacci** [comment]
Assimp CMake file is also broken under Ubuntu LTS 16 and 18.
Another workaround is added for Ubuntu in #10.

I will try to test and use [DART's Findassimp.cmake](https://github.com/dartsim/dart/blob/master/cmake/Findassimp.cmake) as soon as #9 is also fixed.

**Comment by claudiofantacci** [comment]
_Originally posted in #10_

This is an upstream bug that was reported in https://github.com/assimp/assimp/issues/2247 and fixed in https://github.com/assimp/assimp/pull/2253. The PR was merged in December 2018 and is not part of any stable release yet. The current Assimp stable version is `4.1.0`, dates back to December 2017 and is part of Ubuntu Bionic distro. Consequently, this bug is present to **all Assimp version packaged in Ubuntu LTS releases**.

**Comment by claudiofantacci** [comment]
The new version of the library now makes use and require dependency [YCM](https://github.com/robotology/ycm). YCM helps to ship updated CMake files faster either new one or from future CMake releases. The current stable version of YCM provides, [0.10.2](https://github.com/robotology/ycm/releases/tag/v0.10.2), provides an all-new `Findassimp.cmake`. Please use devel version `0.10.100` or newer to have this issue fixed.

**Comment by varoudis** [comment]
> The ASSIMP CMake config files are somewhat broken upstream (not all platform/IDE are affected), but the result is that finding the package with config files is unreliable.
> 
> The following snippet code is an ugly workaround to work under macOS, and in particular with Xcode (compiling using terminal works).
> 
> https://github.com/robotology/superimpose-mesh-lib/blob/ac23148460f4ad5d3f61063dbe10683b298e4463/src/SuperimposeMesh/CMakeLists.txt#L28-L38
> 
> As suggested by @traversaro, we could roll back to [DART's Findassimp.cmake](https://github.com/dartsim/dart/blob/master/cmake/Findassimp.cmake).

for the record this workaround still helps with a MacOS brew install of assimp.
without it you get: ld: library not found for -lassimp
cheers
